### ISSUE TITLE
Tandem Duplications/Fusion of the same gene?

### ISSUE THREAD

**Issue by Jungal10** [WGLab/LongGF#18]
Can we find tandem duplications using LongGF?

For short-reads, using nf-core/rnafusion, Arriba STAR-fusion and FusionCatcher, tandem duplications, can be found.

Is there any workaround for LongGF?

**Comment by liuqianhn** [comment]
@Jungal10 Thank you for being interested in LongGF. This version of LongGF cannot detect tandem duplications.
