### ISSUE TITLE
No fusion  was found      Finish _fg_cand[_gene_pair=0 

### ISSUE THREAD

**Issue by lane-zhao** [WGLab/LongGF#3]
Hi, 
I  have some samples were cDNA ONT sequencing data. I found some fusions by using other tools  and have validated.

Howerver, I  can't found  any fusion by using LongGF.

There has no errors when runing LongFG.  I  installed   longGF by   conda install -c bioconda longgf. 
I used minimap2 to align the reads with parameters:  -t 20 -ax splice -uf -k14
My bam file was  sorted by NAME. 

The result  log file is in the attachment.

[log.file.txt](https://github.com/WGLab/LongGF/files/5375211/log.file.txt)

**Comment by liuqianhn** [comment]
@lane-zhao Thanks for being interested in the tools. It seems that no candidate gene pairs are detected. I can help to figure out why if you are able to share the bam (how large it is). Meanwhile, I would recommend you downloading LongGF in github for now since we do not update LongGF in bioconda yet. Thanks.

**Comment by lane-zhao** [comment]
Hi ,
Thanks for your reply, my bam file is 937M.  I can share my bam file through  a  link if your can give me  an  individual Email accounts , so that it will not be  publicly download.  Many Thanks.  
Lane

**Comment by liuqianhn** [comment]
@lane-zhao my email is liuqianhn_at_gmail.com (please replace `_at_` with `@`).

**Comment by lane-zhao** [comment]
Hi, 
Many thanks for your reply , I have sent a bam file and fasta file to your email. 
Lane

**Comment by mzwaig** [comment]
Hello,

I'm having a similar issue. It looks like longGF is running without issue but nothing is being detected.

Thanks,
Melissa

[MB2018.log](https://github.com/WGLab/LongGF/files/5804255/MB2018.log)

**Comment by liuqianhn** [comment]
@lane-zhao is able to detect gene fusions with the commands I sent via email.

@mzwaig  Although I am not sure the specific reason, one possible reason is that the bam is not sorted by name. Could you please share how you sort the bam and how do you run LongGF?

**Comment by mzwaig** [comment]
No problem. I included secondary alignments and pseudo genes, and lowered the amount of support needed since I don't have any known fusions in my samples. However, even like this nothing is being detected.

#alignment
minimap2 -ax splice -uf -k14 -t 14 $REF_GENOME ${FASTQS} > ${PROJDIR}/alignment/${Sample}.genome.sam ;
samtools view ${PROJDIR}/alignment/${Sample}.genome.sam -b  -@ 14 -o ${PROJDIR}/alignment/${Sample}.genome.bam
samtools sort ${PROJDIR}/alignment/${Sample}.genome.bam -n -@ 14 -o ${PROJDIR}/alignment/${Sample}.genome.namesort.bam;
LongGF ${PROJDIR}/alignment/${Sample}.genome.namesort.bam $GTF 100 30 100 1 1 1 > ${Sample}.log;

**Comment by liuqianhn** [comment]
@mzwaig Your commands look correct to me. I have no idea the reason now. Do you mind sharing me a sample in bam or in fq format to debug what is wrong?

**Comment by mzwaig** [comment]
Sure. I can send you chr22. How should I get it to you?

**Comment by liuqianhn** [comment]
@mzwaig my email is liuqianhn_at_gmail.com (please replace _at_ with @). You can share the data via any way which is convenient for you. By the way, does chr22 contain potential gene fusions?

**Comment by lufeng891109** [comment]
> Hi,
> I have some samples were cDNA ONT sequencing data. I found some fusions by using other tools and have validated.
> 
> Howerver, I can't found any fusion by using LongGF.
> 
> There has no errors when runing LongFG. I installed longGF by conda install -c bioconda longgf.
> I used minimap2 to align the reads with parameters: -t 20 -ax splice -uf -k14
> My bam file was sorted by NAME.
> 
> The result log file is in the attachment.
> 
> [log.file.txt](https://github.com/WGLab/LongGF/files/5375211/log.file.txt)

Hello, I have the same problem with you. Have you solve the problem finally?
Can you send me the command you used?
And any other software you recommand to find fusions?

**Comment by liuqianhn** [comment]
This issue is closed after the reply in email. Feel free to re-open it if there is other further issues

**Comment by zhxiaokang** [comment]
Hi @liuqianhn, I'm using the dataset mentioned in the publication [(PRJNA639366)](https://www.ncbi.nlm.nih.gov/sra/SRR12010483) but got the same issue (no gene fusion detected). I've sent the sorted BAM file and command lines that I used to your email provided above. I appreciate it a lot if you could help to take a look. Thank you!

**Comment by zhxiaokang** [comment]
Here are the commands that I used:
```
# indexing
minimap2 -d Homo_sapiens.GRCh38.dna.toplevel.mmi Homo_sapiens.GRCh38.dna.toplevel.fa

# alignment
## long read -- Oxford Nanopore
minimap2 -a Homo_sapiens.GRCh38.dna.toplevel.mmi -ax splice SRR12010483.fastq > aln_longgf.sam

# sorting and converting SAM to BAM
# samtools sort -n -o aln_sort.bam aln.sam  # Not working
## Error with above command is " no SQ lines present in the header". Try the following commands instead
samtools view -b -T Homo_sapiens.GRCh38.dna.toplevel.fa aln_longgf.sam > aln_longgf.bam
samtools sort -n -o aln_longgf_sort.bam aln_longgf.bam

# gene fusion detection
LongGF aln_longgf_sort.bam Homo_sapiens.GRCh38.103.gtf 100 30 100 > output_longgf_longgf.txt
```

**Comment by mzwaig** [comment]
Could this be an issue with the conda package? I used your exact command and didn't find anything in the test data.

```
fastq-dump SRR12010483
minimap2 -t 3 -ax splice $REF_GENOME SRR12010483.fastq | samtools view --threads 3 -Sb | samtools sort -n -@3 -o SRR12010483.bam
LongGF SRR12010483.bam $GTF 100 50 100 0 0 2 > LongGF.SRR12010483.log
```
[LongGF.SRR12010483.log](https://github.com/WGLab/LongGF/files/6116157/LongGF.SRR12010483.log)

**Comment by liuqianhn** [comment]
Hi, the conda version may not include the latest revision ( I will update it soon).
After compiling, you can use the non-conda version using the full path (the folder of the g++ compile )of the compiled LongGF.

Sent from my iPhone

On Mar 10, 2021, at 8:38 AM, xkzhang <notifications@github.com> wrote:

﻿

Maybe, but I tried to install using "g++" as stated in the installation instruction (tried on three machines: a Mac, a Linux laptop, and a Linux server) but didn't get it to work. That led me to the short-cut, using Conda to install.

**Comment by zhxiaokang** [comment]
Thank you @liuqianhn for updating the package on Conda. It now works for me. But I also found it necessary to set the parameter [Secondary_alignment:0(default)] to 1 to detect gene fusions (otherwise, I got 0 gene fusions from our Nanopore sequencing reads).

**Comment by liuqianhn** [comment]
@zhxiaokang Thanks for your updating. It is great to know it. I will also double check the parameters for  [Secondary_alignment]. Please kindly share your comments after setting Secondary_alignment to 1 since I usually thought more careful checking is needed to filter the gene fusion supported by secondary alignment.

**Comment by liuqianhn** [comment]
@zhxiaokang It is a test testing and experience! Many thanks.
