### ISSUE TITLE
'std::out_of_range' error

### ISSUE THREAD

**Issue by dolittle007** [WGLab/LongGF#4]
Hello.
I ran LongGF for MCF7 FLNC reads.
It raised errors, as followed.
I tried different parameters, the errors still existed. 
Could you help me to figure it out? 
Thank you.

###########################################################
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)

../isoforms/mcf7.bam /home/tywang/database/gencode/gencode.hg38.gtf 100 50 100
Open sam file (../isoforms/mcf7.bam).
Read sam file (../isoforms/mcf7.bam) for scanning multiple-mapped reads.
Handle =0 >> multi_map_reads.size=0 read_len_map.size=0 Time-elapsed=0
Time consumed to read bam: 8.07s
For all reads: reads=518006/518701(99.87) bases=1486425966/1582614941(93.92) ins=74884432(4.73) del=21668672(1.37)
         N10: 8432
         N20: 7785
         N30: 6452
         N40: 5884
         N50: 4545
         N60: 3696
         N70: 3453
         N80: 2558
         N90: 1414
For mapped reads: bases=1486425966/1581434111(93.99) ins=74884432(4.74) del=21668672(1.37)
         N10: 8432
         N20: 7786
         N30: 6453
         N40: 5885
         N50: 4546
         N60: 3696
         N70: 3454
         N80: 2560
         N90: 1415

\# reads with multipe mapping = 3486=3101/518701(0.60)
Open sam file (../isoforms/mcf7.bam).
Read sam file (../isoforms/mcf7.bam) for gene fusion detection.
Handle =0 _fg_cand.size()=0 Time-elapsed=0
Error!! not equal for m140801_014337_42161_c100698070630000001823143403261501_s1_p0/154220/37_8017_CCS 3==2
Error!! not equal for m140810_061610_42161_c100696870310000001823138003261572_s1_p0/48902/7654_65_CCS 2==1

**Comment by liuqianhn** [comment]
@dolittle007 I cannot tell what is wrong based on this error message.
If possible, do you mind sharing me the bam file so that I can test it? Please use my email (liuqianhn@gmail.com) if you can share the file.

**Comment by dolittle007** [comment]
I sent the chr22 only BAM file to your email 5 mins ago.
Hope you can find the bugs soon.

**Comment by liuqianhn** [comment]
Hi @dolittle007 I have downloaded the fasta data via the URL you sent and anlyzed it, and I do not have the issue. Below are the commands I used. Could you please check whether your commands are similar to mine.
```
wget xxxx/newClontech2014.isoseq_flnc.fasta

minimap2 -t 3 -ax splice:hq hg38/hg38.fa ./newClontech2014.isoseq_flnc.fasta | samtools sort -n -@3 -o ./newClontech2014.isoseq_flnc.bam

nohup time -v ./LongGF newClontech2014.isoseq_flnc.bam hg38/gencode.v29.chr_patch_hapl_scaff.annotation.gtf 100 50 100 0 0 2 64  > LongGF.100.50.nops.100r.2021Jan06.64.log &
```

`xxx` is the url you sent to me. You also need to replace `hg38/hg38.fa` and `hg38/gencode.v29.chr_patch_hapl_scaff.annotation.gtf` with your own reference genome and gtf files.

**Comment by dolittle007** [comment]
Thank you.
It works, now.

The problem is that what I input is a coordinate sorted BAM, while LongGF needs a name sorted one.
The Readme of LongGF didn't mention that.

I have one suggestion, can you use the VCF file or BEDPE file as the output file. That will be quite user-friendly.

**Comment by liuqianhn** [comment]
@dolittle007 LongGF needs name-sorted bam. It is a very good suggestion to take vcf or bedpe file as input. I will make it work but should not be ready in a short time. Thanks.

**Comment by liuqianhn** [comment]
Closed since no recent activities. Please reopen if there is any issue.
